name: kit_utilities
description: My test project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  dio: ^4.0.6
  fl_chart: ^0.50.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  intl: ^0.17.0
  provider: ^6.0.3
  rename: ^2.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/icons/appicon.png"
